src/Entity/EducationalCourses.php
<?php

namespace App\Entity;
//  Сущность блока Образовательные курсы
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EducationalCoursesRepository")
 * @Vich\Uploadable
 */
class EducationalCourses
{
  public function __construct()
  {
    $this->updatedAt = new \DateTime();
  }
  /**
   * @ORM\Id()
   * @ORM\GeneratedValue()
   * @ORM\Column(type="integer")
   */
  private $id;

  /**
   * @ORM\Column(type="string", length=255)
   */
  private $title;

  /**
   * @ORM\Column(type="text")
   */
  private $body;

  /**
   * @ORM\Column(type="string", length=255, nullable=true)
   */
  private $full_page;

  /**
   * @ORM\Column(type="integer", nullable=true)
   */
  private $number_of_lessons;

  /**
   * NOTE: This is not a mapped field of entity metadata, just a simple property.
   *
   * @Vich\UploadableField(mapping="icons", fileNameProperty="imageName")
   *
   * @var File
   */
  private $imageFile;

  /**
   * @ORM\Column(type="string", length=255)
   *
   * @var string
   */
  private $imageName;

  /**
   * @ORM\Column(type="datetime", nullable=true)
   *
   * @var \DateTime
   */
  private $updatedAt;

  public function getId(): ?int
  {
    return $this->id;
  }

  public function getTitle(): ?string
  {
    return $this->title;
  }

  public function setTitle(string $title): self
  {
    $this->title = $title;

    return $this;
  }

  public function getBody(): ?string
  {
    return $this->body;
  }

  public function setBody(string $body): self
  {
    $this->body = $body;

    return $this;
  }

  public function getFullPage(): ?string
  {
    return $this->full_page;
  }

  public function setFullPage(string $full_page): self
  {
    $this->full_page = $full_page;

    return $this;
  }

  public function getNumberOfLessons(): ?int
  {
    return $this->number_of_lessons;
  }

  public function setNumberOfLessons(int $number_of_lessons): self
  {
    $this->number_of_lessons = $number_of_lessons;

    return $this;
  }

  public function setImageFile(?File $imageFile = null): void
  {
    $this->imageFile = $imageFile;

    if (null !== $imageFile) {
      // It is required that at least one field changes if you are using doctrine
      // otherwise the event listeners won't be called and the file is lost
      $this->updatedAt = new \DateTimeImmutable();
    }
  }

  public function getImageFile(): ?File
  {
    return $this->imageFile;
  }

  public function setImageName(?string $imageName): void
  {
    $this->imageName = $imageName;
  }

  public function getImageName(): ?string
  {
    return $this->imageName;
  }

  /**
   * @return \DateTime
   */
  public function getUpdatedAt(): \DateTime
  {
    return $this->updatedAt;
  }

  /**
   * @param \DateTime $updatedAt
   */
  public function setUpdatedAt(\DateTime $updatedAt)
  {
    $this->updatedAt = $updatedAt;
  }
}

templates/blocks/static_block/about_block.html.twig
<div  class="about">
  <div class="rightarea-bg"></div>
  <div class="center">
    <div class="rightarea-content">
      <div class="subtitle">
        Об институте
      </div>
      <p>
        Институт Трейдинга и Инвестиций «Феникс» занимается изучением и моделированием ситуаций на финансовых рынках и обучением специалистов в сфере валютно-биржевых торговых инструментов. Подробнее о деятельности Института вы можете узнать в соответствующем разделе.
      </p>
      <a href="/about-page-info" class="btn">Подробнее</a>
    </div>
  </div>
</div>

templates/blocks/static_block/advantages_block.html.twig
<div class="block-advn">
  <div class="center">
    <div class="title">
      НАШИ ПРЕИМУЩЕСТВА
    </div>
    <div class="block-advn-list">
      <div class="block-advn-item">
        <div class="block-advn-img">
          <img src="/img/block-advn-img-1.png" alt="">
        </div>
        <div class="subtitle">
          {{ items.0.title }}
        </div>
        <div class="block-advn-text">
          <p>{{ items.0.body }}</p>
        </div>
      </div>

      <div class="block-advn-item">
        <div class="block-advn-img">
          <img src="/img/block-advn-img-2.png" alt="">
        </div>
        <div class="subtitle">
          {{ items.1.title }}
        </div>
        <div class="block-advn-text">
          <p>{{ items.1.body }}</p>
        </div>
      </div>

      <div class="block-advn-item">
        <div class="block-advn-img">
          <img src="/img/block-advn-img-3.png" alt="">
        </div>
        <div class="subtitle">
          {{ items.2.title }}
        </div>
        <div class="block-advn-text">
          <p>{{ items.2.body }}</p>
        </div>
      </div>
    </div>
  </div>
</div>

templates/blocks/static_block/club_block.html.twig
<div class="club">
  <div class="rightarea-bg"></div>
  <div class="center">
    <div class="rightarea-content">
      <div class="subtitle">
        Клубная жизнь
      </div>
      <p>
        Слушатели и участники Института Трейдинга и Инвестиций «Феникс» – это сообщество единомышленников, которые встречаются, обмениваются опытом и мнениями, вместе проводят время и заводят новые знакомства. Приходите на мероприятия клуба и убедитесь сами!
      </p>
      <a href="/about-page-info/corporate-life" class="btn">Подробнее</a>
    </div>
  </div>
</div>

templates/blocks/static_block/educational_courses_full_block.html.twig
<div class="content-block">
  <p>Специалисты Института Трейдинга и Инвестиций «Феникс» совмещают теоретические занятия с практической
    отработкой навыков. Обучение на курсах трейдеров в Москве проходит как в традиционной очной форме, так и
    дистанционно.</p>

  <div class="course-list">
    {% for item in items %}
      <div class="course-item">
      <div class="course-title">
        <div class="course-title-wrap">
          <span class="course-icn"><img src="/images/icons/{{ item.imageName }}" alt=""></span>
          <span>{{ item.title }}</span>
        </div>
      </div>

      <div class="course-text">
        <div class="course-subtitle">
          <span class="course-icn"><img src="/images/icons/{{ item.imageName }}" alt=""></span>
          <span>{{ item.numberOfLessons }} занятий</span>
        </div>
        <p>
          {{ item.body }}
        </p>
      </div>
      <a href="{{ item.fullPage}}" class="btn">Подробнее</a>
    </div>
    {% endfor %}
  </div>

</div>

templates/blocks/static_block/educational_courses_minimal_block.html.twig
<div class="course">
  <div class="center">
    <div class="title">
      ОБРАЗОВАТЕЛЬНЫЕ КУРСЫ
    </div>
    <div class="course-list">
    {% for item in items %}
      <div class="course-item">
        <div class="course-title">
          {{ item.title }}
        </div>
        <div class="course-text">
          <p>{{ item.body }}</p>
        </div>
        <a href="{{ item.fullPage}}" class="btn">Подробнее</a>
      </div>
    {% endfor %}
    </div>
  </div>
</div>

templates/blocks/static_block/practice_block.html.twig
<div class="practice">
  <div class="leftarea-bg"></div>
  <div class="center">
    <div class="leftarea-content">
      <div class="subtitle">
        Обучение и практика
      </div>
      <p>
        Образовательные программы Института Трейдинга и Инвестиций «Феникс» разработаны для разных уровней подготовки и направлены на формирование и углубление понимания принципов функционирования финансовых рынков и использование этих знаний для получения прибыли от торговли.
      </p>
      <a href="/training-practice" class="btn">Подробнее</a>
    </div>
  </div>
</div>

templates/blocks/static_block/write _all_courses.html.twig
<div class="practice">
  <div class="leftarea-bg"></div>
  <div class="center">
    <div class="leftarea-content">
      <div class="subtitle">
        Запишитесь на любой образовательный курс
      </div>
      <p>
        Образовательные программы Института Трейдинга и Инвестиций «Феникс» разработаны для разных уровней подготовки
        и направлены на формирование и углубление понимания принципов функционирования финансовых рынков и
        использование этих знаний для получения прибыли от торговли.
      </p>
      <a href="/training-practice" class="btn">Подробнее</a>
    </div>
  </div>
</div>