src/Entity/Analytics.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AnalyticsRepository")
 * @Vich\Uploadable
 */
class Analytics
{
  public function __construct()
  {
    $this->updatedAt = new \DateTime();
  }

  /**
   * @ORM\Id()
   * @ORM\GeneratedValue()
   * @ORM\Column(type="integer")
   */
  private $id;

  /**
   * @ORM\Column(type="string", length=255)
   */
  private $title;

  /**
   * @ORM\Column(type="text")
   */
  private $body;

  /**
   * @ORM\ManyToOne(targetEntity="App\Entity\AnalyticsType", inversedBy="analytics_type")
   */
  private $analytics_type;

  /**
   * NOTE: This is not a mapped field of entity metadata, just a simple property.
   *
   * @Vich\UploadableField(mapping="analytics", fileNameProperty="imageName")
   *
   * @var File
   */
  private $imageFile;

  /**
   * @ORM\Column(type="string", length=255)
   *
   * @var string
   */
  private $imageName;

  /**
   * @ORM\Column(type="datetime")
   *
   * @var \DateTime
   */
  private $updatedAt;

  public function getId(): ?int
  {
    return $this->id;
  }

  public function getTitle(): ?string
  {
    return $this->title;
  }

  public function setTitle(string $title): self
  {
    $this->title = $title;

    return $this;
  }

  public function getBody(): ?string
  {
    return $this->body;
  }

  public function setBody(string $body): self
  {
    $this->body = $body;

    return $this;
  }

  public function getAnalyticsType(): ?AnalyticsType
  {
    return $this->analytics_type;
  }

  public function setAnalyticsType(?AnalyticsType $analytics_type): self
  {
    $this->analytics_type = $analytics_type;

    return $this;
  }

  public function setImageFile(?File $imageFile = null): void
  {
    $this->imageFile = $imageFile;

    if (null !== $imageFile) {
      // It is required that at least one field changes if you are using doctrine
      // otherwise the event listeners won't be called and the file is lost
      $this->updatedAt = new \DateTimeImmutable();
    }
  }

  public function getImageFile(): ?File
  {
    return $this->imageFile;
  }

  public function setImageName(?string $imageName): void
  {
    $this->imageName = $imageName;
  }

  public function getImageName(): ?string
  {
    return $this->imageName;
  }

  /**
   * @return \DateTime
   */
  public function getUpdatedAt(): \DateTime
  {
    return $this->updatedAt;
  }

  /**
   * @param \DateTime $updatedAt
   */
  public function setUpdatedAt(\DateTime $updatedAt)
  {
    $this->updatedAt = $updatedAt;
  }
}

src/Entity/AnalyticsType.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AnalyticsTypeRepository")
 */
class AnalyticsType
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type;

  /**
   * @ORM\Column(type="string", length=255)
   */
  private $type_alias;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Analytics", mappedBy="analytics_type")
     */
    private $analytics_type;

    public function __construct()
    {
        $this->analytics_type = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    /**
     * @return Collection|Analytics[]
     */
    public function getAnalyticsType(): Collection
    {
        return $this->analytics_type;
    }

    public function addAnalyticsType(Analytics $analyticsType): self
    {
        if (!$this->analytics_type->contains($analyticsType)) {
            $this->analytics_type[] = $analyticsType;
            $analyticsType->setAnalyticsType($this);
        }

        return $this;
    }

    public function removeAnalyticsType(Analytics $analyticsType): self
    {
        if ($this->analytics_type->contains($analyticsType)) {
            $this->analytics_type->removeElement($analyticsType);
            // set the owning side to null (unless already changed)
            if ($analyticsType->getAnalyticsType() === $this) {
                $analyticsType->setAnalyticsType(null);
            }
        }

        return $this;
    }

  /**
   * @return mixed
   */
  public function getTypeAlias()
  {
    return $this->type_alias;
  }

  /**
   * @param mixed $type_alias
   */
  public function setTypeAlias($type_alias)
  {
    $this->type_alias = $type_alias;
  }
}

templates/blocks/analytics_block.html.twig
<div class="news-subtitle">Аналитика</div>
{% for item in items %}
  <a href="/analytics/{{ item.analyticsType.typeAlias }}/{{ item.id }}" class="news-block-item">
    <span class="news-block-img"><img src="/images/analytics/{{ item.imageName }}" alt=""></span>
    <span class="news-block-content">
      <span class="news-block-title">{{ item.title }}</span>
    </span>
  </a>
{% endfor %}

templates/blocks/calendar_block.html.twig
{% set week =
{
'Monday': 'Пн',
'Tuesday': 'Вт',
'Wednesday': 'Ср',
'Thursday': 'Чт',
'Friday': 'Пт',
'Saturday': 'Су',
'Sunday': 'Вс',
}
%}
{% set month =
{
'January': 'Января',
'February': 'Февраля',
'March': 'Марта',
'April': 'Апреля',
'May': 'Мая',
'June': 'Июня',
'July': 'Июля',
'August': 'Августа',
'September': 'Сентября',
'October': 'Октября',
'November': 'Ноября',
'December': 'Декабря',
}
%}
<div class="calendar">
  <div class="center">
    <div class="title">Расписание занятий</div>
    <div class="column">
      <div class="column-item">
        <div id="calendar" class="calendar-item"></div>
      </div>
      <div class="column-item">
        <div class="calendar-block-list">
          {% for day in data %}
            {% if day.items %}
              <div class="calendar-block-item calendar-block-item--active">
                <div class="calendar-block-date">
                  {{ week[day.date|date("l")] }}, {{ day.date|date("j") }} {{ month[day.date|date("F")] }}
                </div>
                <ul>
                  {% for item in day.items %}
                    <li>
                      <span class="time">{{ item.getEventTime().date|date("H:i") }}</span>
                      <span>{{ item.title }}</span>
                    </li>
                  {% endfor %}
                </ul>
              </div>
              {#{{ dump(day) }}#}
            {% endif %}
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</div>

templates/blocks/footer--block-contacts.html.twig
<div class="block-contacts">
  <div class="center">
    <div class="column">
      <div class="column-item">

        <div class="form">
          <form action="">
            <div class="form__title">
              Контакты
            </div>
            <div class="form__block">
              <div class="column">
                <div class="column-item">
                  <div class="form__line">
                    <label for="name">Ваше имя</label>
                    <input type="text" name="name" placeholder=" ">
                  </div>
                  <div class="form__line">
                    <label for="phone">Телефон</label>
                    <input type="text" name="phone" placeholder=" ">
                  </div>
                  <div class="form__line">
                    <label for="email">E-mail</label>
                    <input type="text" name="email" placeholder=" ">
                  </div>

                  <div class="form__line form__line--checkbox">
                    <input id="agree" type="checkbox">
                    <label for="agree">Согласен на обработку персональных данных </label>
                  </div>
                </div>
                <div class="column-item">
                  <div class="form__line form__line--textarea">
                    <label for="textarea">Текст сообщения</label>
                    <textarea name="textarea" id="" ></textarea>
                  </div>
                  <div class="form__line form__line--submit">
                    <button type="submit" value="">отправить</button>
                  </div>
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>
      <div class="column-item">
        <div class="work-info">
          <div class="work-info-item address">
            <div class="work-info--title">
              Адрес
            </div>

            <div class="work-info-block">
              <span><img src="/img/bg-address.png" alt=""></span>
              109028 г. Москва, Хохловский пер., 16, стр.1 ,офис 16 2 этаж
            </div>
          </div>
          <div class="work-info-item phone">
            <div class="work-info--title">
              Телефон
            </div>

            <a href="tel:88007759820" class="work-info-link ">
              <span><img src="/img/bg-phone.png" alt=""></span>
              8 (800) 775-98-20
            </a>
          </div>
          <div class="work-info-item mail">
            <div class="work-info--title">
              Почта
            </div>

            <a href="mailto:contact@itifenix.ru" class="work-info-link ">
              <span><img src="/img/bg-mail.png" alt=""></span>contact@itifenix.ru
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

templates/blocks/footer.html.twig
{% block block_contacts %}{% include 'blocks/footer--block-contacts.html.twig' %}{% endblock %}
<footer class="footer">
  <div class="center">
    <div class="column">
      <div class="column-item">
        {{ render(controller('App\\Controller\\FooterMenuController::index')) }}
      </div>
      <div class="column-item">
        <div class="footer-info-img">
          <img src="/img/footer-info-img.png" alt="">
        </div>
        <div class="footer-info-text">
          Лицензия на осуществление образовательной деятельности № 037708 от 21.7.2016 года.
        </div>
      </div>
    </div>
  </div>
</footer>

templates/blocks/header.html.twig
<header class="header">
  <div class="header-top">
    <div class="center">
      <div class="column">
        <div class="column-item">
          <div class="work-info">
            <div class="work-info-item mail">
              <a href="mailto:contact@itifenix.ru" class="work-info-link ">
                <span><img src="{{ asset('img/bg-mail.png') }}" alt=""></span>
                contact@itifenix.ru
              </a>
            </div>
            <div class="work-info-item phone">
              <a href="tel:88007759820" class="work-info-link ">
                <span><img src="{{ asset('img/bg-phone.png') }}" alt=""></span>
                8 (800) 775-98-20
              </a>
            </div>
            <div class="work-info-item address">
              <div class="work-info-block">
                <span><img src="{{ asset('img/bg-time.png') }}" alt=""></span>
                Пн-Пт 10-21
              </div>
            </div>
          </div>
        </div>
        <div class="column-item">
          <div class="soc">
            <div class="soc-list">
              <a href="#" class="soc-item soc-item-f" target="_blank"> </a>
              <a href="#" class="soc-item soc-item-vk" target="_blank"> </a>
              <a href="#" class="soc-item soc-item-tw" target="_blank"> </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="nav">
    {{ render(controller('App\\Controller\\HeaderMenuController::index')) }}
  </div>
</header>

templates/blocks/side_bar_block.html.twig
<div class="new-block-list">
  <div class="title">{{ title }}</div>
  {% for item in items %}
    <a href="/about-page-info/news/{{ item.id }}" class="new-block-list-link">{{ item.title }}</a>
  {% endfor %}
</div>